return{
	"EdenEast/nightfox.nvim",
-- 	-- Default options
-- 	require('nightfox').setup({
-- 	  options = {
-- 		-- Compiled file's destination location
-- 		compile_path = vim.fn.stdpath("cache") .. "/nightfox",
-- 		compile_file_suffix = "_compiled", -- Compiled file suffix
-- 		transparent = false,     -- Disable setting background
-- 		terminal_colors = true,  -- Set terminal colors (vim.g.terminal_color_*) used in `:terminal`
-- 		dim_inactive = false,    -- Non focused panes set to alternative background
-- 		module_default = true,   -- Default enable value for modules
-- 		colorblind = {
-- 		  enable = false,        -- Enable colorblind support
-- 		  simulate_only = false, -- Only show simulated colorblind colors and not diff shifted
-- 		  severity = {
-- 			protan = 0,          -- Severity [0,1] for protan (red)
-- 			deutan = 0,          -- Severity [0,1] for deutan (green)
-- 			tritan = 0,          -- Severity [0,1] for tritan (blue)
-- 		  },
-- 		},
-- 		styles = {               -- Style to be applied to different syntax groups
-- 		  comments = "NONE",     -- Value is any valid attr-list value `:help attr-list`
-- 		  conditionals = "NONE",
-- 		  constants = "NONE",
-- 		  functions = "NONE",
-- 		  keywords = "NONE",
-- 		  numbers = "NONE",
-- 		  operators = "NONE",
-- 		  strings = "NONE",
-- 		  types = "NONE",
-- 		  variables = "NONE",
-- 		},
-- 		inverse = {             -- Inverse highlight for different types
-- 		  match_paren = false,
-- 		  visual = false,
-- 		  search = false,
-- 		},
-- 		modules = {             -- List of various plugins and additional options
-- 		  -- ...
-- 		},
-- 	  },
-- 	  palettes = {},
-- 	  specs = {},
-- 	  groups = {},
-- 	}),
-- vim.cmd("colorscheme carbonfox"),
-- 	-- vim.api.nvim_command([[
-- 	-- 	highlight Normal guibg=none
-- 	-- 	highlight NonText guibg=#000000
-- 	-- 	highlight Search guibg=#34eb34
-- 	-- 	highlight CurSearch guibg=#34eb34 guifg=#8426ff
-- 	-- 	highlight WhichKey guifg=#34eb43
-- 	-- 	highlight WhichKeyFloat guibg=#000001
-- 	-- 	highlight WhichKeySeparator guifg=#8426ff
-- 	-- 	highlight TelescopeNormal guibg=#000000
-- 	-- 	highlight TelescopeSelection guibg=#674b94 guifg=#000000
-- 	-- 	highlight TelescopePreviewBorder guifg=#34eb43
-- 	-- 	highlight TelescopeResultsBorder guifg=#34eb43
-- 	-- 	highlight TelescopePromptBorder guifg=#34eb43
-- 	-- 	highlight TelescopeBorder guifg=#e6e600
-- 	-- 	highlight TermCursor guifg=#34eb43
-- 	-- 	highlight NormalFloat guibg=#000000
-- 	-- 	highlight WinSeparator guifg=#8426ff guibg=#000000
-- 	-- 	highlight FloatBorder guifg=#e8eb34 guibg=#000000
-- 	-- 	highlight NotifyBackground guibg=#000000
-- 	-- 	highlight NoiceCmdlinePopupBorder guifg=#34eb43
-- 	-- 	highlight NoiceCmdlineIcon guifg=#e6e600
-- 	-- 	highlight BufferLineFill guibg=#000000
-- 	-- 	highlight StatusLine guibg=#000000
-- 	-- 	highlight NvimTreeWinSeparator guifg=#8426ff guibg=#000000
-- 	-- 	highlight NvimTreeFolderArrowClosed guifg=#34eb43
-- 	-- 	highlight NvimTreeFolderArrowOpen guifg=#34eb43
-- 	-- 	highlight NvimTreeIndentMarker guifg=#e8eb34
-- 	-- 	highlight NvimTreeNormal guibg=NONE ctermbg=NONE
-- 	-- 	highlight NvimTreeRootFolder guibg=NONE ctermbg=NONE guifg=#69FF94
-- 	-- 	highlight CursorLineNr guifg=#e8eb34
-- 	-- 	highlight NvimTreeLineNr guifg=#34eb43
-- 	-- 	highlight LineNr guifg=#D6ACFF
-- 	-- 	highlight LspFloatWinBorder guifg=#e8eb34
-- 	-- 	highlight LspInfoBorder guifg=#e8eb34
-- 	-- ]])
}
